navsat_transform_node:
  ros__parameters:
    two_d_mode: true
    use_odometry_yaw: false        # set true ONLY if /odometry/local orientation is earth-referenced
    wait_for_datum: false
    publish_filtered_gps: false
    zero_altitude: true
    magnetic_declination_radians: 0.0
    yaw_offset: 0.0
    delay: 0.0
