ekf_odom:
  ros__parameters:
    frequency: 50.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom

    # Wheel odom (use velocities only)
    odom0: /odom
    #               x     y     z      r    p    y      vx    vy    vz     wx   wy   wz     ax   ay   az
    odom0_config: [false,false,false, false,false,false, true, false,false, false,false,false, false,false,false]
    odom0_differential: false
    odom0_relative:     false

    # IMU: use ONLY yaw rate (gyro.z). Do NOT fuse orientation.
    imu0: /camera/camera/imu
    imu0_config:   [false,false,false, false,false,false, false,false,false, false,false,true,  false,false,false]
    imu0_differential: false
    imu0_relative:     false
